import streamlit as st
import io
import zipfile

from loader import extract_python_files
from chunker import chunk_python_files
from generator import (
    generate_file_documentation,
    generate_project_readme
)
from repo_loader import clone_repo

st.set_page_config(page_title="AI Code Documentation Generator")

st.title("📘 AI Code Documentation Generator")

# GitHub Repository Input

repo_url = st.text_input("Or enter GitHub repository URL")

if repo_url:
    with st.spinner("Cloning repository..."):
        python_files = clone_repo(repo_url)

    if python_files:
        st.success(f"Loaded {len(python_files)} Python file(s) from repo")
        st.session_state["python_files"] = python_files
    else:
        st.error("No Python files found in repository.")

# File Upload Input

uploaded_files = st.file_uploader(
    "Upload Python file(s) or ZIP",
    type=["py", "zip"],
    accept_multiple_files=True
)

if uploaded_files:
    python_files = extract_python_files(uploaded_files)

    if python_files:
        st.success(f"Loaded {len(python_files)} Python file(s)")

        st.subheader("Files Detected")
        for f in python_files:
            st.write("•", f["filename"])

        st.session_state["python_files"] = python_files
    else:
        st.error("No Python files found.")

# STRICT MODE (AST VALIDATION)

fail_on_validation = st.checkbox(
    "Reject files that fail AST validation (strict mode)"
)

#  GENERATE DOCUMENTATION

if st.button("Generate Documentation"):

    if "python_files" not in st.session_state:
        st.warning("Upload files or provide repo URL first.")
    else:

        python_files = st.session_state["python_files"]

        # ---- Chunking ----
        chunks = chunk_python_files(python_files)

        # ---- Generate Updated Code ----
        with st.spinner("Generating docstrings..."):
            file_docs, cache_flags, validation_flags, retry_counts = generate_file_documentation(chunks,python_files)

        # ---- Generate README ----
        with st.spinner("Generating project overview..."):
            readme, readme_cached = generate_project_readme(chunks)

               #  PROJECT OVERVIEW
       
        st.subheader(" Project Overview")

        if readme_cached:
            st.info("README loaded from Neon cache")
        else:
            st.success("README generated by LLM")

        st.markdown(readme)

               # UPDATED CODE FILES
       
        st.subheader("Updated Files with Docstrings")

        safe_files = {}

        for filename, code in file_docs.items():

            cached = cache_flags.get(filename, False)
            safe = validation_flags.get(filename, False)
            retries = retry_counts.get(filename, 0)

            #  Source Status 

            if cached:
                st.info(f" {filename} — Cached")
            else:
                st.success(f" {filename} — Generated")

            #  Validation Status 

            if safe:
                st.success(" AST validation passed — semantics preserved")
            else:
                if fail_on_validation:
                    st.error(" AST validation failed — file rejected")
                    continue
                else:
                    st.warning(" AST validation failed — original code returned")

            #  Retry Information 

            if retries > 0:
                st.info(f" Regenerated {retries} time(s) due to validation failure")

            #  Show Updated Code 

            st.code(code, language="python")

            # Individual Download 

            st.download_button(
                label=f"⬇️ Download {filename}",
                data=code,
                file_name=filename,
                mime="text/x-python"
            )

            safe_files[filename] = code

        # DOWNLOAD SAFE FILES AS ZIP

        if safe_files:

            zip_buffer = io.BytesIO()

            with zipfile.ZipFile(zip_buffer, "w") as zf:
                for filename, code in safe_files.items():
                    zf.writestr(filename, code)

            st.download_button(
                "⬇️ Download Safe Files (ZIP)",
                zip_buffer.getvalue(),
                "documented_project.zip",
                "application/zip"
            )
        else:
            st.warning("No valid files available for download.")